apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service
spec:
  selector:
    app: hello-world-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use LoadBalancer or NodePort as needed
